development:
  sessions:
    default:
      database: mhero_global_dev
      hosts:
        - localhost:27017
      username: xcm
      options:
        pool_size: 1

      databases:
        database: mhero_world1_dev
        hosts:
          - localhost
        username: xcm
        options:
          pool_size: 1

        database: mhero_world2_dev
        hosts:
          - localhost
        username: xcm
        options:
          pool_size: 1

        database: mhero_world3_dev
        hosts:
          - localhost
        username: xcm
        options:
          pool_size: 1

  options:
    raise_not_found_error: false


test:
  sessions:
    default:
      database: mhero_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: mhero_global_pro
      hosts:
        - gamedev.108km.com:27017
      username: www
      password: www@www
      options:
        pool_size: 1

      databases:
        database: mhero_world1_pro
        hosts:
          - gamedev.108km.com:27017
        username: www
        password: www@www
        options:
          pool_size: 1

